import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "./Components/NavBar";
import { ThemeProvider } from "@/components/theme-provider";
import CartProvider from "./Providers";
import ShoppingCartModal from "./ShoppingCartModal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="system">
          {/* cart provider for chopping cart and stripe prosses */}
          <CartProvider>
            {/* nav bar for large screen  */}
            <NavBar />
            {/* test shoppig cart model */}
            <ShoppingCartModal />
            {children}
          </CartProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
